[workspace]
resolver = "2"
members = ["dirtysocks", "dirtysocks-bin"]

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
debug = false

[profile.profiling]
inherits = "release"
debug = true
