[package]
name = "dirtysocks"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.35.1", features = ["io-util", "rt", "net"] }
thiserror = "1.0.56"
untrusted = "0.9.0"
tracing = "0.1.40"
hickory-resolver = "0.24.1"
seq-macro = "0.3.5"
strum = { version = "0.26.3", features = ["derive"] }
